### ISSUE TITLE
[FEATURE] Beschreibung

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/desktop#11]
Das Repo braucht noch eine Beschreibung.

**Comment by Tobias321** [comment]
Moin moin, die Beschreibung von Core dann auch anpassen?

The desktop repo builds on the core repo and it offers an entry and extension port of it (so ähnlich).

**Comment by AMatutat** [comment]
Ja irgendwie was in der Richtung.

"The pmdungeon is a lightweight, libgdx-based Java framework for developing a 2D Rogue-like. This repository uses the framework, provided by the core-repository, and offers an entry point for developing your own game with libGDX and pmdungeon"

**Comment by cagix** [comment]
# core

The PM-Dungeon is a lightweight Java framework for the development of a 2D-Rouge-like game. This repository contains the actual framework without any launcher implementation and currently uses the [libGDX](https://libgdx.com/) as a backend.

# desktop

The PM-Dungeon is a lightweight Java framework for the development of a 2D-Rouge-like game. This repository provides an entry point for developing your own game with PM-Dungeon [core](https://github.com/PM-Dungeon/core) and [libGDX](https://libgdx.com/).

**Comment by AMatutat** [comment]
ist so gefressen.
Leider kann GitHub in den Beschreibungen wohl keine links darstellen,
