### ISSUE TITLE
[QUESTION] Private fork

### ISSUE THREAD

**Issue by Tobias321** [PM-Dungeon/desktop#12]
@AMatutat @cagix Ich habe hier eine nützliche Beschreibung gefunden: https://gist.github.com/0xjac/85097472043b697ab57ba1b1c7530274

Man kann einen private fork nicht _direkt_ erstellen, aber über den "Umweg" `clone` ist das möglich.

**Comment by cagix** [comment]
ja genau. original-repo lokal clonen, auf github ein neues leeres (und privates) repo erstellen und dieses als weiteres remote in lokalen clone eintragen und pushen. hatten wir da nicht neulich drüber gesprochen?

**Comment by Tobias321** [comment]
> hatten wir da nicht neulich drüber gesprochen?

Ich kann mich nicht mehr genau dran erinnern. 😉

**Comment by Tobias321** [comment]
> ja genau. original-repo lokal clonen, auf github ein neues leeres (und privates) repo erstellen und dieses als weiteres remote in lokalen clone eintragen und pushen.

Aber den Remote-Upstream disablen, nicht das versehentlich etwas in das Dektop-Repo gepusht wird (siehe Schritt 6)

**Comment by cagix** [comment]
**clean-up**: @Tobias321 @AMatutat Was ist mit diesem Ticket? Kann das zu (closed/discarded)? Oder gibt es hier was zu tun -- und wenn ja, wer ist dafür verantwortlich?

**Comment by AMatutat** [comment]
von mir aus zu machen

**Comment by Tobias321** [comment]
Kann zu, war nur als Hinweis gedacht ...
