### ISSUE TITLE
[BUG] main Methode entfernen

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/desktop#16]
Wir geben die `main`-Methode nicht vor. (also tuen wir, sollten wir aber nicht).

Begründung:
- Die Studis müssen dann an den Vorgaben rumfuschen.

**Comment by Tobias321** [comment]
![image](https://user-images.githubusercontent.com/85501570/151416576-e83d48de-e869-40a7-912f-f1ccc4856597.png)

? 😉

**Comment by cagix** [comment]
passiert schon mal

**Comment by AMatutat** [comment]
> ? 😉

ich wollte erst aber hat sich rausgestellt, ich wollte doch nicht.

**Comment by cagix** [comment]
was immer du nimmst, nimm weniger ;)

**Comment by Tobias321** [comment]
> was immer du nimmst, nimm weniger ;)

das willste gar nicht wissen 😉 

BTT: Ich bin mir nicht sicher, ob es noch kompiliert, wenn ich die `main`-Methode rausnehme, weil diese ja auch in der `build.gradle` vorkommt...

**Comment by cagix** [comment]
> BTT: Ich bin mir nicht sicher, ob es noch kompiliert, wenn ich die `main`-Methode rausnehme, weil diese ja auch in der `build.gradle` vorkommt...

hmmm, sollte es nicht möglich sein, ein `.jar` auch ohne `main()` zu erzeugen? machen ja andere auch?

**Comment by Tobias321** [comment]
Stimmt, der `build` funktioniert dennoch :)

**Comment by cagix** [comment]
@AMatutat @Tobias321 Lasst uns noch mal einen Schritt zurücktreten und das ganze Bild betrachten: 

1. Wir sollten in `core` keine `main()` haben, damit die Library (unser `.jar`) tatsächlich eine Lib ist und ohne Probleme verwendet werden kann.
2. Das `desktop` ist die Vorgabe für die Studis. Das forken/clonen die sich und arbeiten darin rum und ergänzen ihre eigenen Klassen.

Jetzt wäre es sinnvoll, wenn sie nicht in den Vorgaben rumwerken müssten, u.a. weil es vielleicht Konflikte gibt, wenn wir die zwischendurch anpassen. D.h. sie sollten sich einen eigenen `DesktopLauncher` schreiben, oder? Oder soll deren Launcher von unserem `DesktopLauncher` ableiten? Falls ersteres, dann sollten wir unsere Klasse `DesktopLauncher` komplett löschen; falls letzteres, sollte unsere Klasse `DesktopLauncher` nicht `final` sein, oder?

**Comment by Tobias321** [comment]
Jein, unser `DesktopLauncher` in der bisherigen Form ist eine Art Utility-Klasse mit einer `run`-Methode, die einen `MainController` übergeben bekommt, und dann das Spiel startet. D. h., die Studis müssen eine eigene Klasse mit einer `main`-Methode anlegen, die bei `gradlew run` aufgerufen wird, und den Einstiegspunkt in der `build.gradle` anpassen. Man könnte darüber nachdenken, a) die Klasse `MyController` aus dem `core` zu schubsen, weil dieser `MainController` tatsächlich selber erstellt werden sollte. Das (a)) sollte problemlos funktionieren.

**Comment by cagix** [comment]
> Jein, unser `DesktopLauncher` in der bisherigen Form ist eine Art Utility-Klasse mit einer `run`-Methode, die einen `MainController` übergeben bekommt, und dann das Spiel startet. D. h., die Studis müssen eine eigene Klasse mit einer `main`-Methode anlegen, die bei `gradlew run` aufgerufen wird, und den Einstiegspunkt in der `build.gradle` anpassen. Man könnte darüber nachdenken, a) die Klasse `MyController` aus dem `core` zu schubsen, weil dieser `MainController` tatsächlich selber erstellt werden sollte. Das (a)) sollte problemlos funktionieren.
> 
> Edit: Oder verstehe ich gerade etwas falsch?

Bin auch grad etwas verwirrt :) 

In `core` sollte nix drin sein, was die Studis irgendwie selbst implementieren sollen. 

Wenn der `DesktopLauncher` in seinem `run()` einen von den Studis implementierten `MainController` bekommt, und die Studis dann selber nochmal irgendwo ein `DesktopLauncher.run(new MainController());` aufrufen müssen, ist das nicht irgendwie "von hinten durch die Brust ins Auge"? Ich meine, dann könnten sie doch ihren `MainController` gleich selbst mit der `run()`-Methode schreiben?

Andererseits ist der Inhalt der `run()`-Methode hässlich :) ... D.h. wir sollten die schon vorgeben. Aber: Der Inhalt von `DesktopLauncher` wird ja nie geändert. Also könnte man diese Klasse mit ins `core` schieben als Teil der Bibliothek? Dann wäre `desktop` quasi nur noch (Beispiel-) Assets und ein Haufen Gradle-Mist als Startpunkt. ... Hätte irgendwie auch was.

**Comment by Tobias321** [comment]
Ich würde gerne @AMatutat s Meinung dazu hören ;)

**Comment by AMatutat** [comment]
Ich möchte nur
```
    public static void main(String[] args) {
        DesktopLauncher.run(new MyController());
    }
```

aus der Vorgabe entfernen und das von den Studis selbst schreiben lassen. Sonst müssen die da rein gehen und `MyController` durch den Namen ihrer Klasse austauschen (die können sie ja nennen wie sie lustig sind).

**Comment by cagix** [comment]
> > Andererseits ist der Inhalt der run()-Methode hässlich :) ... D.h. wir sollten die schon vorgeben. Aber: Der Inhalt von DesktopLauncher wird ja nie geändert. Also könnte man diese Klasse mit ins core schieben als Teil der Bibliothek? Dann wäre desktop quasi nur noch (Beispiel-) Assets und ein Haufen Gradle-Mist als Startpunkt. ... Hätte irgendwie auch was.
> 
> 
> 
> Zwei Einwände:
> 
> 1. Sind im `desktop#run` auch nen paar Konfigurationsgeschichten eingebaut bei den ich mir dann doch vorstellen könnte, dass die von mehr Leuten angefasst werden.

ack.

> 
> 2. Die eigentliche Idee von `core` ist unter anderem ja auch, dass du andere "Frontends" vorschalten kannst. Da finde ich das seltsam schon eins einzubauen. 

aye.

> 
> 3. Anmerkung: Ändert natürlich nichts daran, dass ` DesktopLauncher.run(new MyController());` aufgerufen werden muss

das schon, die klasse selbst wäre dann "aus dem weg" gewesen und nicht mehr zur direkten modifikation verfügbar.


aber punkt 2 ist für mich das totschlag-argument. wir sind zwar im moment irgendwie eng mit libgdx verheiratet, aber das soll ja mittelfristig anders werden und dann macht es wenig sinn, hier die abhängigkeiten noch erst zu vertiefen :)
