### ISSUE TITLE
[FEATURE] GitLab-Toolchain mwe

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/desktop#18]
Wir brauchen ein MWE der angedachten Toolchain (Deploy to Abgabe). 
Für das MWE wäre Relevant
- läuft "über" einen Merge Request
- dummy JUnit-Test
- dummy SpotBugs
- dummy Formatierungs-Check
- die Ergebnisse der Toolchain werden im MR angezeigt und sind mindestens 120 Tage lang einsehbar.

*Note: Gitlab03 verwenden* 

Edit by Tobi:

- [x] #19 
- [x] #20 

Edit 2 by Tobi:

- [x] https://github.com/PM-Dungeon/core/issues/161

Edit 3 by Tobi:

**How to do im GitLab:**
- Wir erstellen eine `.gitlab-ci.yml` im Root-Ordner, anstelle der `.github/workflows/test.yml`
- Wir transferieren den Workflow von `test.yml` nach `.gitlab-ci.yml` mit der GitLab-Syntax
- Dabei können die `gradlew`-Aufrufe 1:1 beibehalten werden
- Die GH-Actions, um die Ergebnisse von JUnit, SpotBugs, Checkstyle und Spotless in PRs zu veröffentlichen, entfallen im GitLab
- Stattdessen müssen wir in die Log-Ausgaben schauen, wenn ein Tool einen Fehler hatte
- Deshalb sollten die Log-Ausgaben im GitLab (und hier) mind. 120 Tage lang gespeichert werden

**Comment by Tobias321** [comment]
Siehe auch Issue #19 und #20

**Comment by Tobias321** [comment]
@cagix Gibt's etwas Neues vom fh gitlab?

**How to do im GitLab:**
- Wir erstellen eine `.gitlab-ci.yml` im Root-Ordner, anstelle der `.github/workflows/test.yml`
- Wir transferieren den Workflow von `test.yml` nach `.gitlab-ci.yml` mit der GitLab-Syntax
- Dabei können die `gradlew`-Aufrufe 1:1 beibehalten werden
- Die GH-Actions, um die Ergebnisse von JUnit, SpotBugs, Checkstyle und Spotless in PRs zu veröffentlichen, entfallen im GitLab
- Stattdessen müssen wir in die Log-Ausgaben schauen, wenn ein Tool einen Fehler hatte
- Deshalb sollten die Log-Ausgaben im GitLab (und hier) mind. 120 Tage lang gespeichert werden

**Comment by cagix** [comment]
> @cagix Gibt's etwas Neues vom fh gitlab?

keine ahnung -- schreibe doch einfach florian und lutz mal direkt an. alles andere ist wieder so "stille post" ;)


> 
> **How to do im GitLab:**
> 
> * Wir erstellen eine `.gitlab-ci.yml` im Root-Ordner, anstelle der `.github/workflows/test.yml`
> * Wir transferieren den Workflow von `test.yml` nach `.gitlab-ci.yml` mit der GitLab-Syntax

das könntest Du ja schon mal vorbereiten ... 

> * Dabei können die `gradlew`-Aufrufe 1:1 beibehalten werden
> * Die GH-Actions, um die Ergebnisse von JUnit, SpotBugs, Checkstyle und Spotless in PRs zu veröffentlichen, entfallen im GitLab
> * Stattdessen müssen wir in die Log-Ausgaben schauen, wenn ein Tool einen Fehler hatte

kann man ein das irgendwie noch mit einem Script zusammenfassen (wenn das überhaupt Sinn macht)?

> * Deshalb sollten die Log-Ausgaben im GitLab (und hier) mind. 120 Tage lang gespeichert werden

ich glaube, 150 tage ist default im github, das würde uns für 4.5 monate tragen, also locker ein semester abdecken. 

aber diese einstellung sollte nur in den studi-repos sein, bei uns laufen die pipelines häufiger, das erzeugt zu viel datenmüll sonst.

**Comment by Tobias321** [comment]
> das könntest Du ja schon mal vorbereiten ...

damit hatte ich doch schon angefangen ;) ...

**Comment by cagix** [comment]
Offene Todos:

- [ ] Wie werden Fehler angezeigt (JUnit, Spotbugs ...) => bitte mal einzeln durchprobieren
- [ ] Speicherdauer der Logs rauskriegen (Doku, Lutz)
- [ ] Config von GH und GL möglichst einheitlich gestalten
- [ ] Stylechecks und Build kann/soll parallel laufen

**Comment by cagix** [comment]
@Tobias321 Bitte vor dem Merge auch die Checkboxen mit abhaken :)

**Comment by cagix** [comment]
> @Tobias321 Bitte vor dem Merge auch die Checkboxen mit abhaken :)

ok, mein fehler, die waren nur im letzten kommentar. vielleicht hätte ich sie ganz oben einfügen sollen ...

**Comment by Tobias321** [comment]
> > @Tobias321 Bitte vor dem Merge auch die Checkboxen mit abhaken :)
> 
> ok, mein fehler, die waren nur im letzten kommentar. vielleicht hätte ich sie ganz oben einfügen sollen ...

Ja, bitte immer im ersten Posting einfügen, sonst denkt man nicht dran und die Automation von GH greift auch nicht ;)

**Comment by cagix** [comment]
> > > @Tobias321 Bitte vor dem Merge auch die Checkboxen mit abhaken :)
> > 
> > 
> > ok, mein fehler, die waren nur im letzten kommentar. vielleicht hätte ich sie ganz oben einfügen sollen ...
> 
> Ja, bitte immer im ersten Posting einfügen, sonst denkt man nicht dran und die Automation von GH greift auch nicht ;)

ich hab irgendwie immer skrupel, anderer leute ersten kommentar zu ändern, @AMatutat findet das auch immer irgendwie seltsam. aber vielleicht muss ich das einfach ablegen :)

**Comment by Tobias321** [comment]
Ach, GH hat doch auch einen Verlauf/Historie:

![image](https://user-images.githubusercontent.com/85501570/152923956-3fd0b643-aac4-4981-ae64-90c9ab47616a.png)

Das passt schon so, so empfindlich bin ich doch nicht :D 

Ok, wenn sich mitten im Text etwas ändern würde, ohne ~~durch Durchstreichen~~ Kenntlich machen, dann wäre das seltsam. ;)

**Comment by Tobias321** [comment]
@cagix Anscheinend werden die Pipelines/Artefakte im GL nur zwei Wochen gespeichert momentan.

**Comment by cagix** [comment]
> @cagix Anscheinend werden die Pipelines/Artefakte im GL nur zwei Wochen gespeichert momentan.

naja, damit kann ich leben:
- wenn die studis sehen wollen, was war, dann sicher eher direkt nach der abnahmen.
- wenn die studis oder wir am ende der veranstaltung ausnahmsweise nochmal was sehen wollen, könnten wir den commit auschecken und den kram nochmal lokal laufen lassen.
