### ISSUE TITLE
[BUG] Milestones missing for PM-Dungeon/desktop

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/desktop#21]
@Tobias321 Bitte die Meilenstein-Definitionen aus `Lecture` oder `core` hier in `desktop` auch eintragen.

**Comment by Tobias321** [comment]
@cagix Siehst du, es war doch gut, dass ich mein Script noch nicht über Bord geworfen habe 😉 

done ✅

**Comment by cagix** [comment]
👍 thx!

**Comment by Tobias321** [comment]
@cagix https://github.com/PM-Dungeon/core/milestone/8 fehlt noch(?); mein Script hatte nur von 1 bis 7 gezählt...

**Comment by cagix** [comment]
> @cagix https://github.com/PM-Dungeon/core/milestone/8 fehlt noch(?); mein Script hatte nur von 1 bis 7 gezählt...

das hab ich jetzt nicht nachgeschaut gehabt, an der stelle hab ich mich auf dich verlassen.
 
dann bastele halt den fehlenden ms nach und schliesse das ticket wieder.

**Comment by Tobias321** [comment]
ne, Moment, warte mal, in `PM-Lecture` gibt es diesen Doku-Milestone nicht...

Frage: Ist der Doku-Milestone nur für das `core`-Repo gedacht oder für `desktop` und `core`?

**Comment by cagix** [comment]
das war fürs framework. da wir das gesplittet haben, sollte es diesen ms in core und in desktop geben imho...

**Comment by Tobias321** [comment]
Ok, fertig. :)

```
1:
Feinkonzept
Sun Oct 31 08:00:00 CET 2021
2:
PM-Dungeon
Fri Dec 31 09:00:00 CET 2021
3:
Deploy-to-Abgabe
Thu Mar 31 09:00:00 CEST 2022
4:
OER-Materialien
Thu Mar 31 09:00:00 CEST 2022
5:
Lehrvideos
Thu Mar 31 09:00:00 CEST 2022
6:
PM-Dungeon: Support, Bug-Fixing, Weiterentwicklung
Fri Jul 01 09:00:00 CEST 2022
7:
E-Assessments und Evaluation
Fri Jul 15 09:00:00 CEST 2022
8:
Dokumentation
Mon Jan 31 09:00:00 CET 2022
```

ist jetzt in `core`, `desktop` und `PM-Lecture`.
