### ISSUE TITLE
[FEATURE] Default close operation

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/desktop#24]
Wenn das Spielfenster durch das Fenster `X` geschlossen wird, wird `finished with non-zero exit value -1` "geworfen". 

In Swing gibt es die `DEFAULT_CLOSE_OPERATION`, evtl gibt es sowas auch für libGDX.

**Comment by AHeinisch** [comment]
Hier soll die Forceexit immernoch vorhanden sein aber nicht mit statuscode -1 sondern 0

**Comment by AHeinisch** [comment]
Beim lösen dieses Issues ist mir aufgefallen das ich mir glaube immer noch nicht ganz sicher bin zu welchen Repo genau was gehört. Diese Erweiterung die ich hinzufüge wäre meines Verständnis eher im core Repo da sie nicht für aufgaben nachträglich abgeändert werden muss. Wiederum kann ich mir vorstellen das es auch gründe geben kann weswegen es im Desktop Repo liegen soll.

Der code würde wie folgt aussehen:
```java
package com.badlogic.gdx.backends.lwjgl; 

import com.badlogic.gdx.ApplicationListener;


public class DungeonApplication extends LwjglApplication {

    protected boolean forceExit = false;
    protected int statusCode = 0;

    /**
     * Creates a new DungeonApplication.
     *
     * @param listener
     * @param config
     * @param statuscode The Exit code which the Operating System needs. Some macOS versions may need -1 to successfully shutdown.
     */
    public DungeonApplication(ApplicationListener listener, LwjglApplicationConfiguration config, int statuscode) {
        super(listener, config);
        if(config.forceExit){
            this.graphics.config.forceExit = false; // the hardcoded System.exit(-1)
            this.forceExit = true; // a different approach
            this.statusCode = statuscode;
        }
    }

    @Override
    protected void mainLoop() {
        super.mainLoop();
        if(forceExit){
            System.exit(statusCode);
        }
    }
}
```
und die Änderung für den Desktoplauncher wird dann sein:
```java 
new DesktopApplication(new LibgdxSetup(mc), config);
```
anstelle von
```java 
new LwjglApplication(new LibgdxSetup(mc), config);
```

Leider muss die DungeonApplication im package "com.badlogic.gdx.backends.lwjgl" liegen da die Konfiguration direkt kopiert wird und somit das forceExit mit default(package-private) zugriffrechten versehen wurde.

Wenn mir einmal wer bitte feedback geben könnte ob sich wirklich die DungeonApplication eher im Desktop Repo befinden soll wäre ich dankbar.

**Comment by Tobias321** [comment]
Ich dachte, man hätte vielleicht diese config https://github.com/PM-Dungeon/desktop/blob/cdaa548155b9aa436058c4139e7ed90a3ea48722/code/desktop/src/desktop/DesktopLauncher.java#L11 anpassen können.

Aber es kann natürlich auch sein, dass wir etwas im core ändern müssen... Ob der DesktopLauncher im Allgemeinen im desktop-Repo liegen sollte, ist noch nicht ganz klar. Ich denke aber schon.

**Comment by AHeinisch** [comment]
Also eigentlich soll ja immer noch ein System.exit ausgeführt werden um mögliche fehlerhaften Threads zu killen sonst wäre es im Desktoplauncher nur folgende Änderung:
```java 
public static void run(MainController mc) {
  LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
  config.width = Constants.WINDOW_WIDTH;
  config.height = Constants.WINDOW_HEIGHT;
  config.foregroundFPS = Constants.FRAME_RATE;
  config.forceExit = false; // <-----
  new LwjglApplication(new LibgdxSetup(mc), config);
}
```

**Comment by Tobias321** [comment]
Hab es mal gerade ausprobiert, bei mir funktioniert es so:

```java
public final class DesktopLauncher {
    public static void run(MainController mc) {
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.width = Constants.WINDOW_WIDTH;
        config.height = Constants.WINDOW_HEIGHT;
        config.foregroundFPS = Constants.FRAME_RATE;
        config.forceExit = false;
        new LwjglApplication(new LibgdxSetup(mc), config);
    }

    public static void main(String[] args) {
        DesktopLauncher.run(new MyController());
    }
}
```

Damit funktioniert `.\gradlew run` und in IntelliJ funktioniert es auch mit einem Klick auf Run main...

Es scheint also wirklich nur diese eine Zeile zu sein...

**Comment by Tobias321** [comment]
@AHeinisch Wenn es bei dir auch funktioniert und es keine "Nebenwirkungen" gibt, dann erstelle bitte einen Pull-Request... 😉

**Comment by AMatutat** [comment]
Wir machen das da https://github.com/PM-Dungeon/desktop/issues/24#issuecomment-1030612180 im `desktop-repo`
