### ISSUE TITLE
[BUG] Name für test.yml 

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/desktop#29]
Die Konfiguration für den Github-Workflow zum Testen heisst `test.yml`, während das Gitlab-Gegenstück `github_ci.yml` heisst. Die beiden Konfigurationen sollten stets synchron sein und entsprechend auch ähnlich benannt werden (wobei der Name bei der Gitlab-Variante afaik fest vorgegeben ist).

Da es das direkte Gegenstück zur Gitlab-CI-Konfig ist, wäre ich für `github_ci.yml` statt `test.yml`.

Siehe auch https://github.com/PM-Dungeon/core/issues/186

**Comment by Tobias321** [comment]
Diese Änderungen sollten zuerst in https://github.com/PM-Dungeon/core gemacht werden und dann in diesem Repo gesynct werden.
