### ISSUE TITLE
[BUG] Bessere Namen für die Jobs in Github-CI test.yml

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/desktop#30]
In der Github-CI-Konfig `test.yml` passen die Job-Namen "spotbugs-test", "checkstyle-test" und "spotless-java-format-test" nicht ganz -- vom Konzept her sind das "Checks".

In der Gitlab-CI-Konfig `.gitlab_ci.yml` wird "spotbugs-job" etc. genutzt. 

Vorschlag: In `test.yml` die selben Namen nutzen, oder aus "spotbugs-test" ein "spotbugs-check" machen. Dann aber auch im `.gitlab_ci.yml` nachziehen.

Siehe auch https://github.com/PM-Dungeon/core/issues/187

**Comment by Tobias321** [comment]
Diese Änderungen sollten zuerst in https://github.com/PM-Dungeon/core gemacht werden und dann in diesem Repo gesynct werden.
