### ISSUE TITLE
[FEATURE] Schnelles erzeugen eines Dummylevels

### ISSUE THREAD

**Issue by jedi101** [PM-Dungeon/desktop#43]
Ich hab jetzt nicht genau in den Code zur Generierung der Level geschaut, mir ist allerdings aufgefallen das bei jedem Build ein neues Level generiert wird. So wie es ausschaut dauert das generieren eines Levels immer unterschiedlich lange. Dies kann dazu führen das ich den Buildprozess gelegentlich manuell gekilled habe weil das erzeugen eines Levels zu lange gedauert hätte. Ich spreche hier manchmal von 12 Minuten+.

Beim testen von kleinen Codeänderungen kann das manchmal ein wenig stören. Und da vom Spiel in der Zeit auch keine Rückmeldung kommt, kann ich mir vorstellen das so mancher Studie dann denkt er hätte einen Fehler gemacht und den Build dann immer wieder abbricht.

Gibt es die Möglichkeit einen bestimmten "Debugseed" eines Levels zu nutzen das in wenigen Sekunden baut? Das wäre für die Entwicklung super nice...

**Comment by AMatutat** [comment]
Benutzt du schon die neue Version des core `2.0.x` ?

**Comment by AMatutat** [comment]
Hmm, seltsam.
Eigentlich läuft das ab version 2.0 deutlich schneller.
Man kann auch Level aus einer .json laden, dafür hab ich aber noch keine Anleitung geschrieben.

**Comment by jedi101** [comment]
Ich denke ein Level aus einer .json zu laden wäre sehr hilfreich. Bekommst auch ein extra ❤ von mir für das Feature.

**Comment by AMatutat** [comment]
Eine richtige Anleitung kann ich morgen schreiben, aber einmal in kurz.

1. Level als json speichern:
Dafür einfach `levelAPI.getCurrentLevel().writeToJSON(*PATH*)`  in der eigenen Implementation hinzufügen.

Die .json muss dann nach "assets/level/files/"

2. Level laden.
Dafür in `setup()` ` levelAPI.setGenerator(new LevelLoader());` hinzufügen.

Jetzt sollte er eigentlich das Level aus der json laden.
Kannst auch mehrere jsons haben, dann wählt er random eins aus.

**Comment by jedi101** [comment]
Welche Library nutzt Du denn für .writeToJSON()?

**Comment by AMatutat** [comment]
gson

**Comment by jedi101** [comment]
Ich nehme mal an das die  .writeToJSON()? noch nicht im Masterbranch gemerged ist bei dem Release 2.0. Bevor ich mir das selbst zusammen klöppele harre ich mal der Dinge.

**Comment by Tobias321** [comment]
> Irgendwo ist auch eine Anleitung, wie man das dann richtig einbindet.

das steht hier https://github.com/PM-Dungeon/core/wiki/Release,-Versionierung-und-Patchnotes#neue-jar-datei-ohne-release-erstellen
