### ISSUE TITLE
[QUESTION] `MyGame` vorgeben

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/desktop#56]
Dieses Repo ist der Einstiegspunkt für die Studis. 
Beim Bearbeiten des Quickstarts ist mir aufgefallen, dass der Weg zum ersten Start relativ lang ist und für die Studierende auch nur aus copy-paste besteht. Zusätzlich müssen sie das Gradle-File anpassen, obwohl die keine Ahnung davon haben, was Gradle ist.

Long story short:
Sollten wir `MyGame extends MainController` vorgeben?
Das umfasst für mich
- Die Klasse selbst
- Das laden des Level 
- Main Methode

Hier im Repo würde dann eine lauffähige Version liegen. 

#58 wäre der Vorschlag wie ich mir das Vorstelle.

**Comment by AMatutat** [comment]
Hier nochmal der Inhalt der Dokumentation zum ersten Start

## Erster Start

In diesen Abschnitt werden alle Schritte erläutert, die zum ersten Start der Anwendung führen.

- Öffnen Sie die den `code`-Folder der Vorgaben als Gradle-Projekt in Ihrer bevorzugten IDE.    - 
- Legen Sie sich eine neue Klasse an. Der Einfachheit halber wird diese Klasse im weiteren Verlauf `MyGame` genannt. Sie können die Klasse aber nennen wie Sie wollen.
- `MyGame` muss von `MainController` erben.
- Implementieren Sie alle notwendigen Methoden. *Hinweis: Weitere Informationen zu diesen Methoden erfolgen im Laufe der Dokumentation.*
    - `setup()`
    - `beginFrame()`
    - `endFrame()`
    - `onLevelLoad()`
- Rufen Sie zum Ende der `setup()`-Methode `levelAPI.loadLevel()` auf um das erste Level zu laden:

  ```java
    @Override
    protected void setup() {
        try {
            levelAPI.loadLevel();
        } catch (NoSolutionException e) {
            System.out.println("Es konnte kein Level geladen werden, bitte den \"assets\" Ordner überprüfen.");
            System.exit(0);
        }
    }
  ```

- Fügen Sie die `main`-Methode hinzu

  ```java
  public static void main(String[] args) {
      DesktopLauncher.run(new MyGame());
  }
  ```

- Passen Sie innerhalb der `code/build.gradle` den Programmeinstiegspunkt (`project.ext.mainClassName = "desktop.DesktopLauncher"`) an und legen Sie ihn auf Ihre Klasse (`MyGame`) fest. Vergessen Sie dabei nicht, auch das Package anzugeben.

Das Spiel sollte nun starten und Sie sollten einen Ausschnitt des Levels sehen können.

Bevor wir nun unseren Helden implementieren sollten wir verstehen, was genau der `MainController` eigentlich ist. Wie der Name schon vermuten lässt, ist dies die Haupt-Steuerung des Spiels. Er bereitet alles für den Start des Spieles vor, verwaltet die anderen Controller und enthält die Game-Loop. Wir nutzen `MyGame` um selbst in die Game-Loop einzugreifen und unsere eigenen Objekte wie Helden und Monster zu verwalten. Der `MainController` ist der Punkt, an dem alle Fäden des Dungeons zusammenlaufen. Im Folgenden wird Ihnen erklärt, wie Sie erfolgreich mit dem `MainController` arbeiten.

**Comment by jedi101** [comment]
@AMatutat Fände ich gut, das nimmt dem Studi evtl. Anfangsschwierigkeiten mit dem Setup etc. und er bekommt sehr schnell ein positives Feedback in form eines lauffähigen pmdungeons.

**Comment by AMatutat** [comment]
Dann machen wir das so. #58
