### ISSUE TITLE
[BUG] Quickstart: Hinweis fehlt, dass das Laden eines Levels dauern kann

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/desktop#81]
Offenbar dauert das Laden eines Levels eine "kleine Ewigkeit", zumindest auf meinem Macbook Air. Man sieht ein schwarzes Fenster und will den Prozess dann schon abschießen, bevor dann doch noch irgendwann ein Level kommt.

Im Quickstart-Guide sollte hervorgehoben werden, dass das Laden eines Levels bis zu 40 Sekunden dauern kann.

Vielleicht sollte auch nochmal überdacht werden, ob man für den Starter nicht einfach feste Level nutzt und erst später zu den generierten Level wechselt.

Aus User-Sicht ist das sehr störend.

**Comment by AMatutat** [comment]
Im Quickstart gibt es einen Abschnitt über die Level. Da steht das drinnen und es wird auch erklärt, wie man auf feste Level wechselt.

**Comment by cagix** [comment]
> @cagix Im Quickstart gibt es einen Abschnitt über den Levelgenerator. Da steht das drinnen und es wird auch erklärt, wie man auf feste Level wechselt. 

Vorschlag: Da kommt ein Satz ganz nach vorn, wo man das erste Mal
was startet.

Vorschlag: Für den Starter bauen wir erstmal feste Level ein, die später ersetzt werden (entweder am Ende de Starters oder als Aufgabe). Ist sicher nicht so schick wie dynamische Level, aber wir sprechen hier über den Starter.

**Comment by AMatutat** [comment]
ok
